### PR TITLE
Improve MQTT

### PR DESCRIPTION
**Pull request by Minims**
- Improve device data in MQTT integration
 - Does not retain camera config by default.

### CODE REVIEW

**Comment by roleoroleo** [comment]
I can't test it now, because my yi_home is down.
But a couple of questions:
- Is get_system_config() necessary? It seems she's never called
- Line 91: variable HTTPD_PORT is empty (maybe it requires get_system_config()?).
- Line 92: echo $DEVICE_DETAILS. Is it a typo?

If I can restore the cam tonight I will test it.

**Comment by roleoroleo** [comment]
We should shed some light on the mqtt world.
There is a big overlapping between mqttv4+mqtt-config and mqtt_adv_homeassistant.sh.

**Comment by Minims** [comment]
> * Is get_system_config() necessary? It seems she's never called
> * Line 91: variable HTTPD_PORT is empty (maybe it requires get_system_config()?).
> * Line 92: echo $DEVICE_DETAILS. Is it a typo?

I have fixed those 3 things :-).

**Comment by Melectro1** [comment]
I have downloaded version yi_dome_0.4.1.tgz and got the camera working. I can see the image in the YI companion app. With my computer I log in with the web browser to the camera and in the CONFIG menu I add Hostname and timezone. At the bottom I click on save configuration, after a short time I get error while saving and after reboot the settings are gone. Enabling swapfile does not help either.
Does anyone know what I am doing wrong? 

Edit: 
I have now downloaded the Yi-cloud firmware and updated another camera with that firmware and in a YI cloud it works to save the configuration. I have even got to activate an Onvif function. This is not possible in the Yi-Dome camera, as I wrote above.

**Comment by ClydePT** [comment]
Hi @Minims @roleoroleo ,
I am able to replicate this issue. I logged in to the web of the camera and tried to do any changes in the settings. After clicking save configuration and moved to a different tab, the changes disappeared.  I confirm if I do the changes via SSH, the changes won't disappear.

**Comment by alienatedsec** [comment]
Are you by any chance a MacOS users?

**Comment by ClydePT** [comment]
No, I’m not a mac user. I’m using windows. I used different web explorers and issue is the same.

**Pull request merged**
