### PR TITLE
compile.proxychains-ng: properly run configure

### PR DESCRIPTION
**Pull request by rofl0r**
now you can also delete the config.mak you ship

### CODE REVIEW

**Comment by alienatedsec** [comment]
@rofl0r It thought it will be irrelevant

```
Compiling proxychains-ng...

checking whether C compiler works ... no
error: install a C compiler and library
rm -f libproxychains4.so
rm -f proxychains4 proxychains4-daemon
rm -f src/common.o src/main.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/rdns.o src/hostsreader.o src/hash.o src/debug.o src/daemon/hsearch.o src/daemon/sblist.o src/daemon/sblist_delete.o src/daemon/daemon.o src/daemon/udpserver.o
rm -f src/version.h
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc  -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/local//lib\" -DSYSCONFDIR=\"/usr/local//etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
cc  -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/local//lib\" -DSYSCONFDIR=\"/usr/local//etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
cc  -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/local//lib\" -DSYSCONFDIR=\"/usr/local//etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc  -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe   -DLIB_DIR=\"/usr/local//lib\" -DSYSCONFDIR=\"/usr/local//etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
In file included from src/libproxychains.c:40:0:
src/core.h:113:10: error: unknown type name ‘GN_NODELEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
          ^~~~~~~~~~~~
src/core.h:113:32: error: unknown type name ‘GN_SERVLEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                ^~~~~~~~~~~~
src/core.h:113:46: error: unknown type name ‘GN_FLAGS_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                              ^~~~~~~~~~
src/core.h:124:8: error: unknown type name ‘getnameinfo_t’
 extern getnameinfo_t true_getnameinfo;
        ^~~~~~~~~~~~~
src/libproxychains.c:64:1: error: unknown type name ‘getnameinfo_t’
 getnameinfo_t true_getnameinfo;
 ^~~~~~~~~~~~~
src/libproxychains.c:811:25: error: unknown type name ‘GN_NODELEN_T’
             char *host, GN_NODELEN_T hostlen, char *serv,
                         ^
src/libproxychains.c:577:26: note: in definition of macro ‘EXPAND’
 #define EXPAND( args...) args
                          ^~~~
src/libproxychains.c:810:1: note: in expansion of macro ‘HOOKFUNC’
 HOOKFUNC(int, getnameinfo, const struct sockaddr *sa, socklen_t salen,
 ^~~~~~~~
src/libproxychains.c:812:13: error: unknown type name ‘GN_SERVLEN_T’
             GN_SERVLEN_T servlen, GN_FLAGS_T flags)
             ^
src/libproxychains.c:577:26: note: in definition of macro ‘EXPAND’
 #define EXPAND( args...) args
                          ^~~~
src/libproxychains.c:810:1: note: in expansion of macro ‘HOOKFUNC’
 HOOKFUNC(int, getnameinfo, const struct sockaddr *sa, socklen_t salen,
 ^~~~~~~~
src/libproxychains.c:812:35: error: unknown type name ‘GN_FLAGS_T’
             GN_SERVLEN_T servlen, GN_FLAGS_T flags)
                                   ^
src/libproxychains.c:577:26: note: in definition of macro ‘EXPAND’
 #define EXPAND( args...) args
                          ^~~~
src/libproxychains.c:810:1: note: in expansion of macro ‘HOOKFUNC’
 HOOKFUNC(int, getnameinfo, const struct sockaddr *sa, socklen_t salen,
 ^~~~~~~~
In file included from src/core.c:38:0:
src/core.h:113:10: error: unknown type name ‘GN_NODELEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
          ^~~~~~~~~~~~
src/core.h:113:32: error: unknown type name ‘GN_SERVLEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                ^~~~~~~~~~~~
src/core.h:113:46: error: unknown type name ‘GN_FLAGS_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                              ^~~~~~~~~~
src/core.h:124:8: error: unknown type name ‘getnameinfo_t’
 extern getnameinfo_t true_getnameinfo;
        ^~~~~~~~~~~~~
src/libproxychains.c: In function ‘setup_hooks’:
src/libproxychains.c:909:76: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
 #define SETUP_SYM_IMPL(X, IS_MANDATORY) do { if (! true_ ## X ) true_ ## X = load_sym( # X, X, IS_MANDATORY ); } while(0)
                                                                            ^
src/libproxychains.c:910:22: note: in expansion of macro ‘SETUP_SYM_IMPL’
 #define SETUP_SYM(X) SETUP_SYM_IMPL(X, 1)
                      ^~~~~~~~~~~~~~
src/libproxychains.c:921:2: note: in expansion of macro ‘SETUP_SYM’
  SETUP_SYM(getnameinfo);
  ^~~~~~~~~
Makefile:93: recipe for target 'src/libproxychains.o' failed
make: *** [src/libproxychains.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/debug.h:19:0,
                 from src/allocator_thread.c:19:
src/core.h:113:10: error: unknown type name ‘GN_NODELEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
          ^~~~~~~~~~~~
src/core.h:113:32: error: unknown type name ‘GN_SERVLEN_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                ^~~~~~~~~~~~
src/core.h:113:46: error: unknown type name ‘GN_FLAGS_T’
          GN_NODELEN_T, char *, GN_SERVLEN_T, GN_FLAGS_T);
                                              ^~~~~~~~~~
src/core.h:124:8: error: unknown type name ‘getnameinfo_t’
 extern getnameinfo_t true_getnameinfo;
        ^~~~~~~~~~~~~
Makefile:93: recipe for target 'src/core.o' failed
make: *** [src/core.o] Error 1
Makefile:93: recipe for target 'src/allocator_thread.o' failed
make: *** [src/allocator_thread.o] Error 1
```

Any ideas?

**Comment by alienatedsec** [comment]
The `gcc` compiler is not defined

**Comment by alienatedsec** [comment]
after defining the compiler it worked, thanks @rofl0r 

```
checking whether C compiler works ... yes
checking whether libc headers are complete ... yes
checking whether C compiler understands -Wno-unknown-pragmas ... yes
checking whether getnameinfo() servlen argument is POSIX compliant (socklen_t) ... no
checking whether getnameinfo() flags argument is unsigned ... yes
checking whether we have GNU-style getservbyname_r() ... yes
checking whether we have pipe2() and O_CLOEXEC ... yes
checking whether we have SOCK_CLOEXEC ... yes
checking whether we have clock_gettime ... yes
checking whether $CC defines __APPLE__ ... no
checking whether $CC defines __FreeBSD__ ... no
checking whether $CC defines __OpenBSD__ ... no
checking whether $CC defines __sun ... no
checking whether $CC defines __HAIKU__ ... no
checking whether we can use -Wl,--no-as-needed ... yes
checking what's the option to use in linker to set library name ... --soname
checking checking whether we can use -ldl ... yes
checking checking whether we can use -lpthread ... yes
Done, now run make && make install
rm -f libproxychains4.so
rm -f proxychains4 proxychains4-daemon
rm -f src/common.o src/main.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/rdns.o src/hostsreader.o src/hash.o src/debug.o src/daemon/hsearch.o src/daemon/sblist.o src/daemon/sblist_delete.o src/daemon/daemon.o src/daemon/udpserver.o
rm -f src/version.h
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/rdns.o src/rdns.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hash.o src/hash.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/debug.o src/debug.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/main.o src/main.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/daemon/hsearch.o src/daemon/hsearch.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/daemon/sblist.o src/daemon/sblist.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/daemon/sblist_delete.o src/daemon/sblist_delete.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/daemon/daemon.o src/daemon/daemon.c
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/daemon/udpserver.o src/daemon/udpserver.c
src/daemon/daemon.c:8:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
arm-hisiv300-linux-uclibcgnueabi-gcc -DSUPER_SECURE -Wno-unknown-pragmas -DGN_NODELEN_T=socklen_t -DGN_SERVLEN_T=socklen_t -DGN_FLAGS_T=unsigned -DHAVE_GNU_GETSERVBYNAME_R -DHAVE_PIPE2 -DHAVE_SOCK_CLOEXEC -DHAVE_CLOCK_GETTIME -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -march=armv5te -mcpu=arm926ej-s -I/opt/arm-hisiv300-linux/target/usr/include -L/opt/arm-hisiv300-linux/target/usr/lib  -DLIB_DIR=\"/lib\" -DSYSCONFDIR=\"/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
arm-hisiv300-linux-uclibcgnueabi-gcc src/common.o src/main.o   -ldl -o proxychains4
arm-hisiv300-linux-uclibcgnueabi-gcc -fPIC -Wl,--no-as-needed -ldl -lpthread  -Wl,--soname,libproxychains4.so \
	 -shared -o libproxychains4.so src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/rdns.o src/hostsreader.o src/hash.o src/debug.o 
arm-hisiv300-linux-uclibcgnueabi-gcc src/daemon/hsearch.o src/daemon/sblist.o src/daemon/sblist_delete.o src/daemon/daemon.o src/daemon/udpserver.o   -o proxychains4-daemon
./tools/install.sh -D -m 644 libproxychains4.so /home/dev/222hack/src/proxychains-ng/_install/lib/libproxychains4.so
./tools/install.sh -D -m 755 proxychains4 /home/dev/222hack/src/proxychains-ng/_install/bin/proxychains4
./tools/install.sh -D -m 755 proxychains4-daemon /home/dev/222hack/src/proxychains-ng/_install/bin/proxychains4-daemon
Installing 'install.proxychains-ng' in the firmware...
```

**Comment by rofl0r** [comment]
i assumed your top-level script would automatically export CC and CFLAGS before including the snippets for a package

**Pull request merged**
